trigger:
- none

parameters:
- name: project_name
  type: string
- name: environment
  type: string
- name: region
  type: string
  default: eastus2

pool: 
  vmImage: ubuntu-latest

stages:
- stage: STG_CREATE_BLOB_STORAGE
  jobs:
  - template: jobs/main.yml
    parameters: 
      project_name: ${{ parameters.project_name }}
      environment: ${{ parameters.environment }}
      region: ${{ parameters.region }}
      app_id: "$(app_id)"
      app_secret: "$(app_secret)"
      tenant: "$(tenant)"