#  This Pipeline Allows you to peform below listed operations full hand.
#  List of operations:
#    - Storage Account Creation [CREATE-STORAGE-ACCOUNT]
#    - Storage Account Deletion [DROP-STORAGE-ACCOUNT]
#    - Full Re-Create [DROP-&-RECREATE]

# Enables/Disables Pipeline Trigger for the branches listed here.
trigger:
- none

# Parameters Initialization for the job
parameters:
- name: environment
  displayName: Environment
  type: string
  values:
    - DEV-TEST
    - UAT
    - PREPROD
    - PROD
- name: region
  displayName: Region/Location
  type: string
  default: eastus2
  values:
    - eastus2
    - eastus
    - southindia
    - westindia
    - westus2
    - westus3
- name: sku
  displayName: Replication Strategy
  type: string
  default: Standard_RAGRS
  values:
    - Premium_LRS
    - Premium_ZRS
    - Standard_GRS
    - Standard_GZR
    - Standard_LRS
    - Standard_RAGRS
    - Standard_RAGZRS
    - Standard_ZRS
- name: stage
  displayName: Stage
  type: string
  default: "DROP & CREATE"
  values:
    - "DROP & CREATE"
    - "CREATE STORAGE ACCOUNT"
    - "DROP STORAGE ACCOUNT"
- name: pool
  displayName: VM-Pool
  type: string
  default: ubuntu-latest
  values:
    - ubuntu-latest
    - windows-latest

# Default Variables Definitiion for the job
variables:
  - template: defaults.yml
    parameters:
      project_name: $(project_name)
      environment: ${{ parameters.environment }}

# Job Stages Definition
stages:
  # Storage Account Creation
  - stage: CREATE_STORAGE_ACCOUNT
    displayName: "STAGE - STORAGE ACCOUNT CREATION"
    pool:
      vmImage: ${{ parameters.pool }}
    condition: or(eq('${{ parameters.stage }}', 'DROP & CREATE'), eq('${{ parameters.stage }}', 'CREATE STORAGE ACCOUNT'))
    jobs:
      - job: job_1
        displayName: "JOB - STORAGE ACCOUNT CREATION"
        steps:
            # Checkout Running Repository
            - checkout: self
              clean: true
            
            # Login Azure Session
            - powershell: |
                & $(build.sourcesDirectory)/azure/login.ps1 -method "SP"
              displayName: az-login
              env:
                AZURE_APP_ID: $(app_id)
                AZURE_APP_SECRET: $(app_secret)
                AZURE_TENANT: $(tenant)
            
            # Blob Storage Creation
            - powershell: |
                & $(build.sourcesDirectory)/blob-storage/scripts/create-blob-storage.ps1
              displayName: create-blob-storage
              env:
                NAME: $(blob_name)
                RESOURCE_GROUP: $(resource_group)
                LOCATION: ${{ parameters.region }}
                SKU: ${{ parameters.sku }}
                ACCESS_TIER: $(access_tier)
            
            # Logout Azure Session
            - powershell: |
                & $(build.sourcesDirectory)/azure/logout.ps1
              displayName: az-logout
