#  This Pipeline Allows you to peform below listed operations full hand.
#  List of Operations:
#    - STORAGE ACCOUNT CREATION
#    - STORAGE ACCOUNT DELETION
#    - ALL OF THE ABOVE

# Enables/Disables Pipeline Trigger for the branches listed here.
trigger:
- none

# Parameters Initialization for the job
parameters:
- name: environment
  displayName: Environment
  type: string
  values:
    - devtest
    - uat
    - preprod
    - prod
- name: region
  displayName: Region/Location
  type: string
  default: eastus2
  values:
    - eastus2
    - eastus
    - southindia
    - westindia
    - westus2
    - westus3
- name: sku
  displayName: Replication Strategy
  type: string
  default: Standard_RAGRS
  values:
    - Premium_LRS
    - Premium_ZRS
    - Standard_GRS
    - Standard_GZR
    - Standard_LRS
    - Standard_RAGRS
    - Standard_RAGZRS
    - Standard_ZRS
- name: stage
  displayName: Stage
  type: string
  default: ALL
  values:
    - ALL
    - STORAGE-ACCOUNT-CREATION
    - STORAGE-ACCOUNT-DELETION
- name: pool
  displayName: VM-Pool
  type: string
  default: ubuntu-latest
  values:
    - ubuntu-latest
    - windows-latest

# Default Variables Definitiion for the job
variables:
  - template: defaults.yml
    parameters:
      project_name: $(project_name)
      environment: ${{ parameters.environment }}

# Job Stages Definition
stages:
  # Storage Account Creation
  - stage: CREATE_STORAGE_ACCOUNT
    displayName: "STAGE - STORAGE ACCOUNT CREATION"
    pool:
      vmImage: ${{ parameters.pool }}
    condition: or(eq('${{ parameters.stage}}', 'ALL'), eq('${{ parameters.stage}}', 'STORAGE-ACCOUNT-CREATION'))
    jobs:
      - job: job_1
        displayName: "JOB - STORAGE ACCOUNT CREATION"
        steps:
            # Checkout Running Repository
            - checkout: self
              clean: true
            
            # Azure Login Task
            - powershell: |
                & $(build.sourcesDirectory)/azure/login.ps1 -method "SP"
              displayName: az-login
              env:
                AZURE_APP_ID: $(app_id)
                AZURE_APP_SECRET: $(app_secret)
                AZURE_TENANT: $(tenant)
            
            # Blob Storage Creation
            - powershell: |
                & $(build.sourcesDirectory)/blob-storage/scripts/create-blob-storage.ps1
              displayName: create-blob-storage
              env:
                NAME: $(blob_name)
                RESOURCE-GROUP: $(resource_group)
                LOCATION: ${{ parameters.region }}
                SKU: ${{ parameters.sku }}
                ACCESS_TIER: $(access_tier)