steps:
  # Checkouts the Pipeline Running Repository
  - checkout: self
    clean: true
  
  - powershell: |
      & $(build.sourcesDirectory)/azure/login.ps1 -method "SP"
    displayName: az-login
  
  - powershell: |
      & $(build.sourcesDirectory)/blob-storage/scripts/create-blob-storage.ps1
    displayName: create-blob-storage