parameters:
- name: project_name
  type: string
- name: environment
  type: string
- name: region
  type: string
- name: app_id
  type: string
- name: app_secret
  type: string
- name: tenant
  type: string

jobs:
- job: Job_1
  displayName: JOB_CREATE_BLOB_STORAGE
  pool:
    vmImage: ubuntu-latest
  steps:
    - template: ../tasks/main.yml
      parameters: 
      project_name: ${{ project_name }}
      environment: ${{ environment }}
      region: ${{ region }}
      app_id: ${{ app_id }}
      app_secret: ${{ app_secret }}
      tenant: ${{ tenant }}