parameters:
- name: project_name
  type: string
- name: environment
  type: string
- name: region
  type: string
- name: tenant
  type: string
- name: sku
  type: string
- name: resource_group
  type: string
- name: app_id
  type: string
- name: app_secret
  type: string

jobs:
- job: Job_1
  displayName: JOB_CREATE_BLOB_STORAGE
  pool:
    vmImage: ubuntu-latest
  steps:
    - template: ../tasks/main.yml
      parameters: 
        environment: ${{ parameters.environment }}
        region: ${{ parameters.region }}
        sku: ${{ parameters.sku }}
        project_name: "${{ parameters.project_name }}"
        app_id: "${{ parameters.app_id }}"
        app_secret: "${{ parameters.app_secret }}"
        tenant: "${{ parameters.tenant }}"
        resource_group: "${{ parameters.resource_group }}"