parameters:
- name: project_name
  type: string
- name: environment
  type: string
- name: region
  type: string
# - name: app_id
#   type: string
# - name: app_secret
#   type: string
# - name: tenant
#   type: string
- name: sku
  type: string

jobs:
- job: Job_1
  displayName: JOB_CREATE_BLOB_STORAGE
  pool:
    vmImage: ubuntu-latest
  steps:
    - template: ../tasks/main.yml
      parameters: 
        project_name: ${{ parameters.project_name }}
        environment: ${{ parameters.environment }}
        region: ${{ parameters.region }}
        sku: ${{ parameters.sku }}
      variables:
        app_id: "$(app_id)"
        app_secret: "$(app_secret)"
        tenant: "$(tenant)"
        resource_group: "$(resource_group)"